# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GreetingGenerator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GreetingGenerator
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  target 'GreetingGeneratorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
