# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftWithDataSource' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    git: 'https://github.com/ReactiveX/RxSwift.git', 
  							  commit:'ecb9ba58435f703c361b3906ee29c2d45a605a4a'
  pod 'RxCocoa',    git: 'https://github.com/ReactiveX/RxSwift.git', 
  commit:'ecb9ba58435f703c361b3906ee29c2d45a605a4a'
  # Pods for RxSwiftWithDataSource

end
