# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todoListWithRxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for todoListWithRxSwift
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  target 'todoListWithRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'RxBlocking', '~> 3.0'
  pod 'RxTest',     '~> 3.0'
  end

end
